Repository Arsollo/Soen-341-Project, pull requests merged in 2021-10, with the labels that each got.

#18 Making necessary changes to features description
  README.md
Labels: documentation

#25 Had to modify the code to make it work
  question.py
Labels: bug

#24 Fixes and funtional Q&A
  Question.py
  about.html
  ask.html
  home.html
  layout.html
  question.html
  question_view.html
Labels: user story, Web-User story
