Repository Arsollo/Soen-341-Project, pull requests merged in 2021-12, with the labels that each got.

#51 User profile page is now functional & CSS is more coherent & User can…
  .DS_Store
  Question.py
  Templates/about.html
  Templates/edit_profile.html
  Templates/edit_questions.html
  Templates/home.html
  Templates/layout.html
  Templates/profile.html
  site.db
  static/main.css
  static/website_style.css
Labels: enhancement, user story

#55 updates on travis.yml file
  travis.yml
Labels: testing

#56 Answers are now ranked by votes
  .DS_Store
  Question.py
  Templates/Edit_user_information.html
  Templates/question_view.html
  site.db
  static/website_style.css
Labels: duplicate, enhancement, Client-Request

#60 deleted unnecessary lines
  travis.yml
Labels: testing

#59 Complete Build - Patch 6.5
  Question.py
  Templates/edit_profile.html
  Templates/edit_questions.html
  Templates/home.html
  Templates/profile.html
  Templates/question_view.html
  forms.py
  site - Copy.db
  site.db
Labels: enhancement, Client-Request, Bug Fix

#61 Testing files and edit for travis.yml
  tests/test_forms.py
  tests/test_question.py
  travis.yml
Labels: testing

#63 Implemented vote button limitations
  .DS_Store
  Question.py
  Templates/question_view.html
  __pycache__/forms.cpython-310.pyc
  site.db
  static/website_style.css
Labels: Client-Request, Bug Fix

#68 website no longer crashes if submit button is pressed with an empty f…
  .DS_Store
  Question.py
  Templates/login.html
  Templates/question_view.html
  __pycache__/forms.cpython-310.pyc
  site.db
Labels: Bug Fix

#72 Cleaned up the code and added more meaningful comments
  .DS_Store
  Question.py
  Templates/about.html
  Templates/answered.html
  Templates/edit_profile.html
  Templates/edit_questions.html
  Templates/home.html
  Templates/layout.html
  Templates/login.html
  Templates/profile.html
  Templates/question.html
  Templates/question_view.html
  Templates/register.html
  __pycache__/forms.cpython-310.pyc
  forms.py
  site.db
  static/main.css
  static/website_style.css
Labels: documentation

#70 configuration of BaseTestCase
  config.py
Labels: testing

#71 Unit Test
  tests/test.py
Labels: bug, testing
