Repository Arsollo/Soen-341-Project, pull requests merged in 2021-11, with the labels that each got.

#33 Upload for bug fix
  Question.py
Labels: Bug Fix

#36 Registration and login functionality
  Question.py
  Templates/about.html
  Templates/answered.html
  Templates/ask.html
  Templates/home.html
  Templates/layout.html
  Templates/login.html
  Templates/question.html
  Templates/question_view.html
  Templates/register.html
  Templates/website.html
  site.db
  static/main.css
  static/website_style.css
Labels: enhancement, Web-User story

#21 Create travis.yml
  travis.yml
Labels: testing

#38 Delete website.html
  Templates/website.html
Labels: invalid

#42 Added semi-functional voting functionality
  .DS_Store
  Question.py
  Templates/about.html
  Templates/ask.html
  Templates/profile.html
  Templates/question_view.html
  site.db
Labels: enhancement

#46 Basline profile association with login
  Question.py
  Templates/profile.html
  Templates/question_view.html
  site.db
Labels: enhancement, Web-User story

#50 Added user_profile functionalities and made a big improvement to the …
  .DS_Store
  Question.py
  Templates/ask.html
  Templates/home.html
  Templates/profile.html
  Templates/question_view.html
  site.db
  static/website_style.css
Labels: enhancement
